package com.bluntsoftware.app.modules.signshop.repository;

import com.bluntsoftware.app.modules.signshop.domain.Customersigns;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Customersigns.
* @author autogenerated
*/

@Repository("signshopCustomersignsRepository")
@Qualifier("signshop")
//@RepositoryRestResource(collectionResourceRel="signshop.Customersigns", path="signshop/Customersigns")
public interface CustomersignsRepository extends GenericRepository<Customersigns,Integer>  {

}