package com.bluntsoftware.app.modules.signshop.repository;

import com.bluntsoftware.app.modules.signshop.domain.Customer;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Customer.
* @author autogenerated
*/

@Repository("signshopCustomerRepository")
@Qualifier("signshop")
//@RepositoryRestResource(collectionResourceRel="signshop.Customer", path="signshop/Customer")
public interface CustomerRepository extends GenericRepository<Customer,Integer>  {

}