package com.bluntsoftware.app.modules.signshop.repository;

import com.bluntsoftware.app.modules.signshop.domain.Material;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Material.
* @author autogenerated
*/

@Repository("signshopMaterialRepository")
@Qualifier("signshop")
//@RepositoryRestResource(collectionResourceRel="signshop.Material", path="signshop/Material")
public interface MaterialRepository extends GenericRepository<Material,Integer>  {

}