package com.bluntsoftware.app.modules.signshop.repository;

import com.bluntsoftware.app.modules.signshop.domain.Sign;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Sign.
* @author autogenerated
*/

@Repository("signshopSignRepository")
@Qualifier("signshop")
//@RepositoryRestResource(collectionResourceRel="signshop.Sign", path="signshop/Sign")
public interface SignRepository extends GenericRepository<Sign,Integer>  {

}